New Docker command to generate DockerFiles of specified services
SamagraX-Stencil/stencil-cli pull request #34
Opened 2024-06-20 10:00 UTC by Savio629

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/SamagraX-Stencil/stencil/issues/135#event-13223410367

## What is the new behavior?
`stencil docker <services...>`
where <services> = monitoring logging temporal 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2024-06-27 16:38 UTC, Savio629 commented
Updated existing test and implemented e2e test for docker command

2024-06-30 11:26 UTC, Savio629 commented
### Completed:
- Implemented Docker Command
    - Tooling specific setup
    - À la Carte setup
- Updated stencil cli docs - Docker command
- Updated existing test and implemented e2e test for docker command



### In the progress:
- `--path` argument remaining in À la Carte setup
- Update docker-start.sh

2024-07-11 03:08 UTC, Savio629 commented
README.md for Docker Command


## Docker Command

```
stencil docker <services...> [options]
stencil do <services...> [options]
```
**Description**

Creates a docker service/container for given prompt.
-  Tooling specific setup
    - Creates a folder with the given `<service>` inside docker directory
- À la Carte setup
    - Creates a docker compose or updates existing docker compose with desired `<service>`

**Arguments**

| Argument  |  Description |
|-----------|--------------|
|  `<service>`	 | The name of the new project |

**Options**

| Option  |  Description |
|-----------|--------------|
|  `--path [path]`	 | The path where the docker compose will be generated |


Note: Docker command supports multiple services at a time.

**Services**

-  Tooling specific setup


| Name  | Alias  |  Description |
|---|---|---|
|  `logging` | `lg`  | Generates a docker service for logging |
|  `monitoringService` |`ms`   | Generates a docker service for monitoring  |
|  `temporal` |  `tp` |  Generates a docker service for temporal |

- À la Carte setup


| Name  | Alias  |  Description |
|---|---|---|
|  `postgres` | `pg`  | Generate a docker compose for postgres |
|  `hasura` |`hs`   | Generate a docker compose for hasura  |

2024-08-09 20:12 UTC, techsavvyash requested changes

2024-08-09 20:12 UTC, techsavvyash commented on Docker-readme.md
> +Creates a docker service/container for given prompt.
are we supporting prompts?

2024-08-09 20:12 UTC, techsavvyash commented on actions/docker.action.ts
> +      new SchematicOption('language', 'ts'),
why have we hardcoded to `ts`

2024-08-09 20:12 UTC, techsavvyash commented on actions/new.action.ts
> +    // );
remove comments

2024-08-09 20:12 UTC, techsavvyash commented on actions/new.action.ts
> +    // );
remove comments

2024-08-09 20:12 UTC, techsavvyash commented on actions/new.action.ts
> +        await createRegistry(projectDirectory, shouldInitializePrima,shouldInitializeUserService,shouldInitializeMonitoring,shouldInitializeTemporal,shouldInitializeFileUpload);
why are we removing logging everywhere?

2024-08-09 20:12 UTC, techsavvyash commented on actions/new.action.ts
> +//   inputs.find((options) => options.name === 'monitoringService');
remove comments

2024-08-09 20:12 UTC, techsavvyash commented on actions/new.action.ts
> +//   inputs.find((options) => options.name === 'logging');
remove comments

2024-08-09 20:12 UTC, techsavvyash commented on actions/new.action.ts
> +  // }
remove comments

2024-08-09 20:12 UTC, techsavvyash commented on actions/new.action.ts
> +  // }
remove comments

2024-08-09 20:12 UTC, techsavvyash commented on actions/new.action.ts
> +// };
remove comments

2024-08-10 15:38 UTC, Savio629 commented on Docker-readme.md
> +Creates a docker service/container for given prompt.
Not yet

2024-08-10 15:38 UTC, Savio629 commented on Docker-readme.md
> +Creates a docker service/container for given prompt.
Will update the readme

2024-08-10 15:40 UTC, Savio629 commented on actions/docker.action.ts
> +      new SchematicOption('language', 'ts'),
this was already present with new command
It is the default language which is pushed if no language is given by the user

2024-08-10 15:40 UTC, Savio629 commented on actions/new.action.ts
> +    // );
Wanted to confirm about removal of logging 
Will remove the comments

2024-08-10 15:42 UTC, Savio629 commented on actions/new.action.ts
> +        await createRegistry(projectDirectory, shouldInitializePrima,shouldInitializeUserService,shouldInitializeMonitoring,shouldInitializeTemporal,shouldInitializeFileUpload);
As of right now logging only make changes on docker level not on code level so I shifted logging to docker service command and removed from existing setup

2024-08-20 10:49 UTC, Savio629 commented on actions/new.action.ts
> +        await createRegistry(projectDirectory, shouldInitializePrima,shouldInitializeUserService,shouldInitializeMonitoring,shouldInitializeTemporal,shouldInitializeFileUpload);
@techsavvyash

2024-08-24 13:33 UTC, Savio629 commented
- [x] Resolved all the comments
- [x] Added `minio` and `fusionauth` in the docker command
- [x] Tested the commands well

2024-09-19 15:07 UTC, Savio629 commented
![image](https://github.com/user-attachments/assets/da033686-d91d-486e-b4f4-b4dc88be2e4b)

2024-09-21 10:46 UTC, techsavvyash approved these changes

2024-09-21 10:47 UTC, merged